# Generated by Django 5.1 on 2024-08-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
