FROM nginx:latest

RUN apt-get update && \
    apt-get install -y nginx vim openssl && \
    mkdir -p /var/www/html/

RUN apt-get install -y curl

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -subj "/C=KR/ST=Seoul/L=Gaepo/O=42Seoul/OU=Develop/CN=kichlee's"

COPY conf/default.conf /etc/nginx/conf.d/default.conf

COPY tools/script.sh /tmp/script.sh


RUN chmod 600 /etc/nginx/ssl/server.key

RUN chmod 777 /tmp/script.sh

EXPOSE 443

CMD [ "/tmp/script.sh"]
