# Generated by Django 5.1 on 2024-09-06 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
