# Generated by Django 5.1 on 2024-09-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0002_twofactorauth_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='last_verified_at',
        ),
    ]
