# Generated by Django 4.0.5 on 2024-07-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '사용자 권한',
                'db_table': 'user_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='이메일')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일자')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.userrolemodel', verbose_name='사용자 권한')),
            ],
            options={
                'verbose_name_plural': '회원정보',
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
