# Generated by Django 5.1 on 2024-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usermodel_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
